'use strict'

var m = require('markdownscript')
var h2 = m.h2
var code = m.code
var emphasis = m.emphasis
var link = m.link
var paragraph = m.paragraph
var script = code => m('markdownScript', { code })

module.exports = (pkg) => {
  var children = [
    script(`'# ' + pkg.name + ' ' + shields.apply(null, ${pkg.badges})`),
    script('pkg.description'),
    script('installation()')
  ]

  if (pkg.usage) {
    children = children.concat([
      h2(['Usage']),
      code({
        lang: pkg.usage.language,
        value: pkg.usage.content
      })
    ])
  }

  if (pkg.scripts.test) {
    children = children.concat([
      h2(['Tests']),
      code({
        lang: 'sh',
        value: 'npm install\nnpm test'
      })
    ])
  }

  if (pkg.testOutput) {
    children = children.concat([
      code({
        value: pkg.testOutput
      })
    ])
  }

  children = children.concat([
    script('dependencies()'),
    script('devDependencies()'),
    script('license()')
  ])

  if (pkg.footer) {
    children = children.concat([
      paragraph([
        emphasis([
          'Generated by ',
          link({ url: 'https://github.com/zeke/package-json-to-readme' }, [
            'package-json-to-readme'
          ])
        ])
      ])
    ])
  }

  var ast = m.root(children)
  return ast
}
